name: Deploy Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: apt-get install -y mkdocs

      - name: Build and deploy
        run: mkdocs gh-deploy --force

